export * from "./salle.controller";
export * from './auth.controller';
export * from './exerciseType.controller';
export * from './badge.controller'
export * from './userBadge.controller'
export * from './challenge.controller'
export * from './userChallenge.controller'
export * from './communityChallenge.controller'
export * from './user.controller'